-- MySQL Script generated by MySQL Workbench
-- Wed May  1 20:50:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cats` (
  `idcats` INT NOT NULL,
  PRIMARY KEY (`idcats`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`smallCats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`smallCats` (
  `idsmallCats` INT NOT NULL,
  `russianBlue` INT NULL,
  `maineCoon` INT NULL,
  `cats` INT NOT NULL,
  PRIMARY KEY (`idsmallCats`, `cats`),
  INDEX `cats_idx` (`cats` ASC) VISIBLE,
  CONSTRAINT `cats`
    FOREIGN KEY (`cats`)
    REFERENCES `mydb`.`cats` (`idcats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bigCats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bigCats` (
  `idbigCats` INT NOT NULL,
  `lion` INT NULL,
  `leopard` INT NULL,
  `cats` INT NOT NULL,
  PRIMARY KEY (`idbigCats`, `cats`),
  INDEX `cats_idx` (`cats` ASC) VISIBLE,
  CONSTRAINT `cats`
    FOREIGN KEY (`cats`)
    REFERENCES `mydb`.`cats` (`idcats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
